### ISSUE TITLE
[Bug] Checking the results of the system

### ISSUE THREAD

**Issue by KanapongAiamtip** [codee-club/contributors#2]
# 🐞 Bug Report 🐞

When sending a code, sometimes the result is correct, sometimes the system checks 0 and sends another 100 when it is the same file. And at some time Doing different methods and results in the same way. But the system does not check some, check occasionally

**Comment by charles-allen** [comment]
Hi Kanapong! Thank you for reporting this bug. 

Please could you help us by giving a specific example; could you add the following to your report:
- URL​ for the problem
- The code you're submitting

You can add code using: ```

**Comment by KanapongAiamtip** [comment]
can you check it
https://codee.club/254275-20s2/loops-and-conditionals/6
[image: Screen Shot 2564-01-16 at 00.30.01.png]

**Comment by charles-allen** [comment]
> can you check it https://codee.club/254275-20s2/loops-and-conditionals/6 [image: Screen Shot 2564-01-16 at 00.30.01.png]

Hi again Kanupong.

1) I cannot see the screenshot you shared; I guess GitHub doesn't support uploading images by email. Maybe you could post it again using the GitHub website?

2) I cannot find your account. Please could you copy-paste the URL to your profile:

<img width="840" alt="Screen Shot 2021-01-16 at 09 59 21" src="https://user-images.githubusercontent.com/31621095/104795526-b0c6aa80-57e1-11eb-9ca9-81d0579731d3.png">

**Comment by KanapongAiamtip** [comment]
https://codee.club/profiles/x4kWFNuYJoAUwe2f7Q8P
![Screen Shot 2564-01-16 at 00 30 01](https://user-images.githubusercontent.com/75485361/104799456-da8fc980-5801-11eb-82cf-351c728ad871.png)

**Comment by charles-allen** [comment]
Thanks! I'll take a look this evening!

**Comment by charles-allen** [comment]
Hi again Kanapong/Natchanon!

## Cause of issue

I found your submissions & I've worked out why you observed different behavior. Although the code you submitted was identical, the filename was not:

**Attempt 1: "Q6.java"**
```java
public class F { ... } // does not compile (filename must match class) => 0%
```

**Attempt 2: "F.java"**
```java
public class F { ... } // does compile & your code passed the tests => 100%
```

## Resolution

Since it's quite important for Java developers to follow this file-naming constraint, I expect we will not change this grading behavior; you can choose any class name, but the filename must match (for Java).

However, I think our UI should communicate the cause of failure more clearly. **I've prioritized one of our planned new features: "Display result details (modal)"**. This new feature will let your click to open a result to see more details - failure type & detailed comparison (diff) for any failing public tests.

**We aim to include this feature in next week's deploy (release 0.0.6)**

**Comment by KanapongAiamtip** [comment]
I would like to be able to download the code that we sent as well, and I would like to give you a preview of all my friends, everyone who has made this event

**Comment by charles-allen** [comment]
> I would like to be able to download the code that we sent as well

Great idea. I can probably add a download link to the modal by next release! I'll have a think about displaying the code within the browser too (in a future release).

> and I would like to give you a preview of all my friends, everyone who has made this event

I don't understand this. Could you please explain a little more? (maybe write it in Thai)

**Comment by KanapongAiamtip** [comment]
I want the Rank Show All people to do this event 

![Screen Shot 2564-01-17 at 19 47 51](https://user-images.githubusercontent.com/75485361/104843420-25dad280-58fd-11eb-81e0-f833ae59ee18.png)
That Example Same the old grader

**Comment by charles-allen** [comment]
We show the top 10 on the Activity page: https://codee.club/254275-20s2/loops-and-conditionals
- There are 3 tabs: `Global`, `Section`, `Friends`
- You can "follow" people to add them to your `Friends` top 10

Is "follow" what you need?

If not, can you give me examples of how you use the old leaderboard? What are you trying to achieve? What can't you do on the new site? Understanding your goals helps me to find the best solution!

<img width="500" alt="Screen Shot 2021-01-17 at 21 14 01" src="https://user-images.githubusercontent.com/31621095/104845647-13ff2c80-5909-11eb-809d-5f2bd4292136.png">

**Comment by KanapongAiamtip** [comment]
It okay for  3 tabs: Global, Section, Friends. Can it show more than 10 people? on the section tab and the friends tab the old  leaderboars show all people
![Screen Shot 2564-01-17 at 22 51 13](https://user-images.githubusercontent.com/75485361/104848304-f1741000-5916-11eb-9999-fc5c86467407.png) 
This show 108 people

**Comment by charles-allen** [comment]
> If not, can you give me examples of how you use the old leaderboard?

I understand your suggested solution but there may be other solutions that fit better with our design. I want to understand your goal/objective; **why do you want all 100+ people?**
- Are you looking for friends scores?
- Is there something impossible or inconvenient?
- Do you need to lookup other people's scores to tell them?

I need to understand the goal. Please describe use cases / scenarios.

**Comment by KanapongAiamtip** [comment]
> I understand your suggested solution but there may be other solutions that fit better with our design. I want to understand your goal/objective; **why do you want all 100+ people?**

Oh thx Nevermid if the ui fit in your design thx you so much you can show 10 people it okay  I just  give advice thx you very much for see my advice

**Comment by charles-allen** [comment]
@KanapongAiamtip - FYI: "Results details" will go LIVE this evening in the `0.0.6` release :)
![Screen Shot 2021-01-20 at 16 11 06](https://user-images.githubusercontent.com/31621095/105152728-244a1e00-5b3a-11eb-85ba-8f8d8cab386d.png)

Exclusive preview :D

![Screen Shot 2021-01-20 at 16 15 45](https://user-images.githubusercontent.com/31621095/105153472-0f21bf00-5b3b-11eb-8562-e4b42d6d8da9.png)
![Screen Shot 2021-01-20 at 16 16 36](https://user-images.githubusercontent.com/31621095/105153480-121caf80-5b3b-11eb-8193-3b766c0a2a0d.png)
![Screen Shot 2021-01-20 at 16 16 50](https://user-images.githubusercontent.com/31621095/105153483-134ddc80-5b3b-11eb-9068-b1de74f15203.png)
![Screen Shot 2021-01-20 at 16 16 53](https://user-images.githubusercontent.com/31621095/105153486-147f0980-5b3b-11eb-8bfb-bf23d58579ce.png)
![Screen Shot 2021-01-20 at 16 16 55](https://user-images.githubusercontent.com/31621095/105153490-1517a000-5b3b-11eb-9d93-053fa1f72df7.png)
![Screen Shot 2021-01-20 at 16 16 58](https://user-images.githubusercontent.com/31621095/105153491-15b03680-5b3b-11eb-9cb2-72eb5d34eaca.png)
![Screen Shot 2021-01-20 at 16 17 01](https://user-images.githubusercontent.com/31621095/105153493-1648cd00-5b3b-11eb-8fe1-e96ec1300eba.png)
![Screen Shot 2021-01-20 at 16 17 04](https://user-images.githubusercontent.com/31621095/105153495-1648cd00-5b3b-11eb-90ee-fab303452a15.png)
![Screen Shot 2021-01-20 at 16 17 11](https://user-images.githubusercontent.com/31621095/105153499-16e16380-5b3b-11eb-93b6-7f3d28bf8e1e.png)

**Thank you for supporting Codee :)**
