### ISSUE TITLE
[Bug] QR Code pops up when `Choose` new profile picture button is clicked.

### ISSUE THREAD

**Issue by grindarius** [codee-club/contributors#5]
# 🐞 Bug Report 🐞

- [x] This is a bug, not a feature request:  
      https://github.com/codee-club/contributors/issues/new
- [x] I could not find it in existing issues:  
      https://github.com/codee-club/contributors/issues?q=is%3Aissue

*************************

## ➊ Summary
- When I click on the `Choose` button in order to change my profile picture. the QR Code pops up.

## ➋ Reproduction steps
1. Go to you profile in https://codee.club
2. Click choose button in your profile picture circle.

## ➌ Expected behavior
- The file selector should pop up.

## ➍ Actual behavior
- The file selector actually pop up, also with the QR Image

## ➎ Screenshots
![GIF 28-06-2021 10-50-01](https://user-images.githubusercontent.com/60266519/123578450-16db4300-d800-11eb-9d3c-7d3857105b8a.gif)

**Comment by charles-allen** [comment]
Thank you for reporting this! 
Very clear report :)

**Comment by charles-allen** [comment]
@grindarius - This should be fixed in 0.0.9

**Comment by charles-allen** [comment]
Now live!
