### ISSUE TITLE
[Bug] Cannot follow specific user.

### ISSUE THREAD

**Issue by grindarius** [codee-club/contributors#6]
# 🐞 Bug Report 🐞

- [x] This is a bug, not a feature request:  
      https://github.com/codee-club/contributors/issues/new
- [x] I could not find it in existing issues:  
      https://github.com/codee-club/contributors/issues?q=is%3Aissue

*************************

## ➊ Summary
I found that I cannot actually follow [this user](https://codee.club/profiles/lQFvyboByVsCs0YlQbkO) specifically. The follow button just keeps spinning and pops out without following the user. This problem seems to be happening to all users that are trying to follow this account too.

## ➋ Reproduction steps
1. Go to [this user.](https://codee.club/profiles/lQFvyboByVsCs0YlQbkO)
2. Click 'Follow' under his profile picture.

## ➌ Expected behavior
Expected my username to pop up in follower list and the button showing 'Unfollow'
![default-follow-behavior](https://user-images.githubusercontent.com/60266519/123982335-210e6480-d9ed-11eb-8ade-f325f43c857c.gif)

## ➍ Actual behavior
My username popped up for a second and then gone.
![cannot follow phet](https://user-images.githubusercontent.com/60266519/123982396-31beda80-d9ed-11eb-846c-cacf0f2c98be.gif)

Does not work when trying to follow the user from my profile's Followers tab too.
![phet bug](https://user-images.githubusercontent.com/60266519/123983052-c295b600-d9ed-11eb-9dba-17808f5b7448.gif)

## ➎ Screenshots
Further inspections in Network tab in DevTools. Found 3 database calls
![log inspect](https://user-images.githubusercontent.com/60266519/123982517-4d29e580-d9ed-11eb-852c-b17e145acb32.gif)

Upon console inspection.
![image](https://user-images.githubusercontent.com/60266519/123992218-a138c800-d9f5-11eb-8517-fcef6e285828.png)

**Comment by charles-allen** [comment]
@grindarius - Do you see any errors in the console?

**Comment by grindarius** [comment]
> @grindarius - Do you see any errors in the console?

I have included the console inspection in the post now

**Comment by charles-allen** [comment]
Not what I expected...

**Comment by charles-allen** [comment]
@grindarius - Can you please Ctrl+F5, and see if you still have an issue?

**Comment by grindarius** [comment]
@charles-allen I jus rejoined the website and seems like it's working fine now. I have tried to follow him
- through another friend's follower list.
- through a notification.
- follow him directly.

I can follow him on every method I could think of so it looks like we can close this now.

**Comment by charles-allen** [comment]
Fixed in 0.0.10 :)
