### ISSUE TITLE
[Bug] Write a clear & specific titled wanted full rights to what I asked some one for help but never downloaded anything

### ISSUE THREAD

**Issue by Davidharvey123** [codee-club/contributors#8]
# 🐞 Bug Report 🐞

- [ ] This is a bug, not a feature request:  
      https://github.com/codee-club/contributors/issues/new
- [ ] I could not find it in existing issues:  
      https://github.com/codee-club/contributors/issues?q=is%3Aissue

*************************

## ➊ Summary
    Please give a clear and concise description of what the bug is

## ➋ Reproduction steps
    1. Go to ...
    2. Click on ...
    3. Scroll down to ...

## ➌ Expected behavior
    What you expected to happen (but didn't)

## ➍ Actual behavior
    What actually happened

## ➎ Screenshots
    Screenshots/video demonstrating the issue

**Comment by charles-allen** [comment]
Closed as spam - this user also spammed here:

- https://github.com/codee-club/contributors/issues/3
- https://github.com/github/feedback/discussions/4921#discussioncomment-1195214
